"""Descarga reproducible del Fire Weather Index histórico de CEMS/EWDS."""

from __future__ import annotations

import os
from collections import defaultdict
from datetime import date
from pathlib import Path

import cdsapi
import geopandas as gpd
import numpy as np
import pandas as pd
import xarray as xr
from dotenv import load_dotenv

DATASET = "cems-fire-historical-v1"
EWDS_API_URL = "https://ewds.climate.copernicus.eu/api"
FWI_VARIABLE = "fire_weather_index"
# [norte, oeste, sur, este]. Incluye toda Galicia y un pequeño margen de borde.
GALICIA_AREA = [44.0, -10.0, 41.0, -6.0]
FWI_FILE_PATTERN = "fwi_galicia_*.nc"

CANONICAL_DATACUBE_VARIABLE_FLAGS = {FWI_VARIABLE: True}
DATACUBE_VARIABLE_FLAGS = CANONICAL_DATACUBE_VARIABLE_FLAGS

FWI_METADATA = {
    "long_name": "Canadian Fire Weather Index",
    "units": "1",
    "source": "Copernicus CEMS Fire danger indices historical data",
    "description": (
        "Daily physical fire-danger baseline generated by CEMS from ERA5 forcing. "
        "It does not represent observed ignitions."
    ),
    "time_contract": "Same-day historical fire-danger index; no temporal shift applied.",
    "spatial_interpolation": (
        "Nearest-neighbour interpolation from the native 0.25 degree CEMS grid to 1 km cells, "
        "following the IberFire baseline procedure."
    ),
}

FWI_ENCODING = {"zlib": True, "complevel": 4, "dtype": "float32"}


def _dates_for_year(year: int, start_date: date, end_date: date) -> list[date]:
    """Devuelve las fechas del intervalo que pertenecen a ``year``."""
    first = max(date(year, 1, 1), start_date)
    last = min(date(year, 12, 31), end_date)
    if first > last:
        return []

    return [
        date.fromordinal(ordinal)
        for ordinal in range(first.toordinal(), last.toordinal() + 1)
    ]


def _cubre_intervalo(path: Path, first: date, last: date) -> bool:
    """Indica si un fichero FWI contiene todos los días solicitados.

    Los ficheros crudos se conservan sin recortarlos: una descarga hecha para
    un intervalo parcial debe poder reutilizarse cuando después se solicite un
    año completo. La selección exacta se realiza al cargar FWI para el cubo.
    """
    try:
        with xr.open_dataset(path) as dataset:
            if "valid_time" not in dataset.coords:
                return False
            available = pd.DatetimeIndex(dataset["valid_time"].values).normalize()
    except (OSError, ValueError):
        return False

    required = pd.date_range(first, last, freq="D")
    return required.isin(available).all()


def _fechas_faltantes(path: Path, requested: list[date]) -> list[date]:
    """Devuelve solo las fechas que no están en un archivo anual ya existente."""
    if not path.exists() or path.stat().st_size == 0:
        return requested
    try:
        with xr.open_dataset(path) as dataset:
            available = pd.DatetimeIndex(dataset["valid_time"].values).normalize()
    except (KeyError, OSError, ValueError):
        return requested
    return [item for item in requested if pd.Timestamp(item) not in available]


def _agrupar_fechas_por_mes(dates: list[date]) -> dict[int, list[date]]:
    """Agrupa fechas por mes para no enviar días inválidos a EWDS.

    La API interpreta ``month`` y ``day`` como un producto cartesiano. Por
    tanto, una petición anual con el día 31 incluiría por error el 31 de
    febrero. Se emite una petición por mes con sus días reales.
    """
    grouped: dict[int, list[date]] = defaultdict(list)
    for item in dates:
        grouped[item.month].append(item)
    return dict(grouped)


def _combinar_fragmentos_fwi(
    output_path: Path, fragments: list[Path], first: date, last: date
) -> None:
    """Une fragmentos mensuales con un archivo parcial y reemplaza al final."""
    sources = ([output_path] if output_path.exists() and output_path.stat().st_size > 0 else [])
    sources.extend(fragments)
    datasets = [xr.open_dataset(path) for path in sources]
    try:
        merged = xr.concat(datasets, dim="valid_time", join="exact").sortby("valid_time")
        _, positions = np.unique(merged["valid_time"].values, return_index=True)
        merged = merged.isel(valid_time=np.sort(positions)).load()
    finally:
        for dataset in datasets:
            dataset.close()

    temporary_path = output_path.with_suffix(".complete.nc")
    if temporary_path.exists():
        temporary_path.unlink()
    merged.to_netcdf(temporary_path)
    if not _cubre_intervalo(temporary_path, first, last):
        temporary_path.unlink()
        raise ValueError(f"La descarga FWI no cubre todo el intervalo {first} a {last}.")
    temporary_path.replace(output_path)


def descargar_fwi_historico(
    output_dir: str | Path,
    start_date: date = date(2019, 1, 1),
    end_date: date = date(2023, 12, 31),
) -> list[Path]:
    """Descarga FWI diario para Galicia, separado por año y con caché verificable.

    Los datos proceden del producto CEMS histórico basado en ERA5. FWI es el
    único índice descargado porque se utiliza como baseline físico, siguiendo
    IberFire; sus componentes no se incorporan al datacubo en esta fase.
    """
    load_dotenv()
    api_key = os.getenv("COPERNICUS_CDS_API_KEY")

    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    client: cdsapi.Client | None = None
    outputs: list[Path] = []

    for year in range(start_date.year, end_date.year + 1):
        dates = _dates_for_year(year, start_date, end_date)
        if not dates:
            continue
        output_path = output_dir / f"fwi_galicia_{year}.nc"
        missing_dates = _fechas_faltantes(output_path, dates)
        if not missing_dates:
            outputs.append(output_path)
            continue

        if client is None:
            if not api_key:
                raise RuntimeError("Falta COPERNICUS_CDS_API_KEY en el archivo .env.")
            client = cdsapi.Client(url=EWDS_API_URL, key=api_key)
        # La API combina ``month`` y ``day`` entre sí; por ello descargamos
        # fragmentos mensuales con días válidos y solo reemplazamos el anual
        # una vez que todos han llegado y su cobertura está verificada.
        fragments: list[Path] = []
        try:
            for month, month_dates in _agrupar_fechas_por_mes(missing_dates).items():
                temporary_path = output_path.with_name(
                    f"{output_path.stem}_{month:02d}.download.nc"
                )
                if temporary_path.exists():
                    temporary_path.unlink()
                fragments.append(temporary_path)
                client.retrieve(
                    DATASET,
                    {
                        "product_type": "reanalysis",
                        "variable": [FWI_VARIABLE],
                        "dataset_type": "consolidated_dataset",
                        "system_version": ["4_1"],
                        "year": [str(year)],
                        "month": [f"{month:02d}"],
                        "day": [f"{item.day:02d}" for item in month_dates],
                        "area": GALICIA_AREA,
                        "grid": "0.25/0.25",
                        "data_format": "netcdf",
                        "download_format": "unarchived",
                    },
                ).download(str(temporary_path))
            _combinar_fragmentos_fwi(output_path, fragments, dates[0], dates[-1])
        finally:
            for fragment in fragments:
                if fragment.exists():
                    fragment.unlink()
        outputs.append(output_path)

    return outputs


def listar_archivos_fwi(
    raw_dir: str | Path,
    start_date: str | date,
    end_date: str | date,
) -> list[Path]:
    """Comprueba que existe un NetCDF de FWI para cada año del intervalo."""
    start = pd.Timestamp(start_date).date()
    end = pd.Timestamp(end_date).date()
    files_by_year: dict[int, Path] = {}
    for path in Path(raw_dir).glob(FWI_FILE_PATTERN):
        try:
            year = int(path.stem.rsplit("_", maxsplit=1)[-1])
        except ValueError:
            continue
        if start.year <= year <= end.year:
            if year in files_by_year:
                raise ValueError(f"Hay más de un archivo FWI para {year}.")
            files_by_year[year] = path

    missing = [str(year) for year in range(start.year, end.year + 1) if year not in files_by_year]
    if missing:
        raise FileNotFoundError("Faltan archivos FWI para los años: " + ", ".join(missing))
    return [files_by_year[year] for year in range(start.year, end.year + 1)]


def cargar_fwi_historico(
    files: list[Path], start_date: str | date, end_date: str | date
) -> xr.Dataset:
    """Une los ficheros anuales CEMS y normaliza sus coordenadas para Galicia."""
    datasets = [xr.open_dataset(path) for path in files]
    try:
        fwi = xr.concat(datasets, dim="valid_time", join="exact").sortby("valid_time").load()
    finally:
        for dataset in datasets:
            dataset.close()

    if "fwinx" not in fwi.data_vars:
        raise ValueError("El producto CEMS no contiene la variable FWI esperada 'fwinx'.")
    fwi = fwi[["fwinx"]].rename({"valid_time": "time", "fwinx": FWI_VARIABLE})
    # CEMS codifica la longitud en el intervalo [0, 360); la rejilla del proyecto
    # y los centroides de Galicia usan [-180, 180].
    longitude = ((fwi.longitude + 180) % 360) - 180
    fwi = fwi.assign_coords(longitude=longitude).sortby("longitude")
    return fwi.sel(time=slice(str(start_date), str(end_date))).astype(np.float32)


def interpolar_fwi_al_grid(
    raw_dir: str | Path,
    cube_path: str | Path,
    grid_path: str | Path,
    output_path: str | Path,
    start_date: str | date,
    end_date: str | date,
    inclusion_flags: dict[str, bool] | None = None,
) -> None:
    """Añade FWI diario interpolado por vecino más cercano a la capa dinámica.

    El archivo de destino ya contiene ERA5 interpolado. FWI se escribe como una
    variable adicional, sin modificar las demás capas meteorológicas.
    """
    flags = DATACUBE_VARIABLE_FLAGS if inclusion_flags is None else inclusion_flags
    if not flags.get(FWI_VARIABLE, False):
        return

    files = listar_archivos_fwi(raw_dir, start_date, end_date)
    fwi = cargar_fwi_historico(files, start_date, end_date)
    try:
        expected_dates = pd.date_range(start_date, end_date, freq="D")
        actual_dates = pd.DatetimeIndex(fwi.time.values)
        if not actual_dates.equals(expected_dates):
            raise ValueError("La cobertura temporal FWI no coincide con el intervalo del datacubo.")

        destination = Path(output_path)
        if not destination.exists():
            raise FileNotFoundError(
                f"No existe la capa meteorológica de destino: {destination}. Procesa ERA5 primero."
            )

        with xr.open_dataset(cube_path) as cube, xr.open_dataset(destination) as meteorology:
            if FWI_VARIABLE in meteorology.data_vars:
                return
            grid = gpd.read_file(grid_path)
            active = grid.loc[grid["is_galicia"] == 1].copy()
            centroids = gpd.GeoSeries(active.geometry.centroid, crs=active.crs).to_crs("EPSG:4326")
            latitude = xr.DataArray(centroids.y.to_numpy(), dims="cell")
            longitude = xr.DataArray(centroids.x.to_numpy(), dims="cell")
            rows = (active["cell_id"].to_numpy() // cube.sizes["x"]).astype(int)
            columns = (active["cell_id"].to_numpy() % cube.sizes["x"]).astype(int)
            values = fwi[FWI_VARIABLE].sel(
                latitude=latitude, longitude=longitude, method="nearest"
            ).values.astype(np.float32)
            output_dates = pd.DatetimeIndex(meteorology.time.values)
            output_time = meteorology.time.load()
            y_coordinates = cube.y.load()
            x_coordinates = cube.x.load()
            date_positions = {date: position for position, date in enumerate(output_dates)}
            positions = [date_positions[date] for date in actual_dates]
            full = np.full(
                (len(output_dates), cube.sizes["y"], cube.sizes["x"]), np.nan, dtype=np.float32
            )
            for fwi_position, output_position in enumerate(positions):
                full[output_position, rows, columns] = values[fwi_position]
            interpolated = xr.Dataset(
                {FWI_VARIABLE: (("time", "y", "x"), full)},
                coords={"time": output_time, "y": y_coordinates, "x": x_coordinates},
            )
            interpolated[FWI_VARIABLE].attrs = FWI_METADATA
        try:
            interpolated.to_netcdf(
                destination,
                mode="a",
                encoding={FWI_VARIABLE: FWI_ENCODING},
            )
        except OSError as error:
            # Algunos archivos NetCDF grandes abiertos por un visor externo no
            # admiten ``mode='a'`` en Windows. Reescribir a un temporal evita
            # modificar el original hasta que la nueva copia esté completa.
            if "HDF error" not in str(error):
                raise
            _escribir_fwi_por_reemplazo_atomico(destination, interpolated)
    finally:
        fwi.close()


def _escribir_fwi_por_reemplazo_atomico(destination: Path, fwi: xr.Dataset) -> None:
    """Añade FWI mediante un NetCDF temporal cuando el modo append falla."""
    temporary = destination.with_suffix(".with_fwi.nc")
    if temporary.exists():
        temporary.unlink()
    with xr.open_dataset(destination) as existing:
        if FWI_VARIABLE in existing:
            return
        merged = existing.assign(fwi)
        encoding = {
            name: {
                key: value
                for key, value in existing[name].encoding.items()
                if key
                in {
                    "zlib",
                    "complevel",
                    "shuffle",
                    "fletcher32",
                    "contiguous",
                    "chunksizes",
                    "dtype",
                    "_FillValue",
                }
            }
            for name in existing.data_vars
        }
        encoding[FWI_VARIABLE] = FWI_ENCODING
        merged.to_netcdf(temporary, encoding=encoding)
    temporary.replace(destination)


def actualizar_fwi_en_productos_existentes(
    raw_dir: str | Path,
    spatial_cube_path: str | Path,
    grid_path: str | Path,
    meteorology_cube_path: str | Path,
    datacube_path: str | Path,
    inclusion_flags: dict[str, bool] | None = None,
) -> tuple[pd.Timestamp, pd.Timestamp]:
    """Incorpora FWI a las salidas existentes sin reconstruir el datacubo.

    Añade la variable tanto a la capa meteorológica intermedia como al cubo
    final. El intervalo se toma del cubo final para no depender de constantes
    de configuración ni alterar el contrato temporal de EGIF ya construido.

    Returns:
        Fechas inicial y final que se han incorporado.
    """
    datacube_path = Path(datacube_path)
    if not datacube_path.exists():
        raise FileNotFoundError(f"No existe el datacubo final: {datacube_path}")

    with xr.open_dataset(datacube_path) as datacube:
        if "is_galicia" not in datacube:
            raise ValueError("El datacubo final no contiene la máscara 'is_galicia'.")
        dates = pd.DatetimeIndex(datacube.time.values)
        if dates.empty:
            raise ValueError("El datacubo final no contiene fechas.")
        start_date, end_date = dates.min(), dates.max()

    descargar_fwi_historico(raw_dir, start_date.date(), end_date.date())
    for destination in (meteorology_cube_path, datacube_path):
        interpolar_fwi_al_grid(
            raw_dir=raw_dir,
            cube_path=spatial_cube_path,
            grid_path=grid_path,
            output_path=destination,
            start_date=start_date.date(),
            end_date=end_date.date(),
            inclusion_flags=inclusion_flags,
        )
    return start_date, end_date
